### PR TITLE
Update for Julia 1.x

### PR DESCRIPTION
**Pull request by mpastell**
I updated a few deprecations, parsing seems to work well with few simple tests.

### CODE REVIEW

**Comment by stevengj** [comment]
Thanks!  You should also change the REQUIRE file to list Julia 0.7.

**Comment by mpastell** [comment]
Thanks, I updated  REQUIRE. 

Could you register this package? I'm trying to add support for citations to `Weave.jl` and using this package to parse bibtex. https://github.com/mpastell/Weave.jl/pull/185

**Comment by simonbyrne** [comment]
@stevengj Would it be possible to register this package? Also I noticed that issues are currently disabled (I'm not sure if this was intentional or not), and the link to the documentation is broken (it points to the repositories previous location, which 404s).

**Comment by stevengj** [comment]
We could register the package.

Is there an organization that this repo should be transferred to?  I haven't touched it for a long time.

**Comment by stevengj** [comment]
Issues are disabled because this is a fork of a package initially created by @bramtayl, which has now disappeared.

(I can't remember why the original disappeared?)

**Comment by stevengj** [comment]
Note that the original was, I think, a translation of https://github.com/ptigas/bibpy/blob/master/bibpy/bib.py, which should be credited if so?

**Comment by stevengj** [comment]
The sad thing is that I remember doing a whole bunch of work to postprocess the raw bibtex contents that all seems to be gone now — I think I submitted them as PRs to @bramtayl and then deleted the branches from my fork once they were merged?

**Comment by bramtayl** [comment]
My original code was indeed based on https://github.com/ptigas/bibpy/blob/master/bibpy/bib.py but I think the code ended up being rather different. I deleted the original package along with a bunch of others when 1.0 rolled out as a way to clear out clutter (maybe not the smartest of my ideas). I was thinking at the time if I was ever to return to the project that I'd start by porting something like [this](https://github.com/brechtm/citeproc-py) which has the ability to parse not only BibTeX but also do a bunch of other cool stuff. But right now I'm personally at the point  where I'm satisfied to list ISBN, OCLC, or DOI numbers and let my readers look up the rest.

**Comment by stevengj** [comment]
In principle, we could automate the process of converting a DOI to a citation in many cases — https://crosscite.org/docs.html

(But this doesn't work for cited material that doesn't have a DOI.)

**Comment by stevengj** [comment]
But it would still be nice to have a bibTeX parser for Julia in any case.

**Comment by simonbyrne** [comment]
One option would be https://github.com/JuliaIO. I'm not an admin there though.

**Comment by dpsanders** [comment]
There's https://github.com/JuliaTeX/

**Comment by stevengj** [comment]
@mykelk, would you mind posting a clone of this package on JuliaTeX, and giving access to me and the other contributors?

I can't actually move stevengj/BibTeX.jl, since this is a fork of the original BibTeX.jl, which was unfortunately deleted from github (see above).

**Comment by mykelk** [comment]
@stevengj I just invited you to JuliaTeX so you should be able to move it there. I believe you should be able to add contributors as well. Let me know if this is not the case.

**Comment by stevengj** [comment]
I've made a request to github support to detach this repo into an independent repository rather than a fork.  Once that is done, I can transfer it to JuliaTeX.

**Comment by stevengj** [comment]
Done.  Apparently it was already detached automatically when the original repo was deleted, since this was the oldest fork.

**Pull request merged**
